### ISSUE TITLE
any plans to add a license for this repo?

### ISSUE THREAD

**Issue by danbri** [Faur/CTRNN#2]
see also https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by Faur** [comment]
Added the Creative Commons Attribution-ShareAlike 2.5 Generic (CC BY-SA 2.5) license: https://creativecommons.org/licenses/by-sa/2.5/.

Hope you find this useful.

**Comment by danbri** [comment]
Thanks!

**Comment by Faur** [comment]
@danbri just out of curiosity - what are you working on/planning to do? I was in Jun Tani's lab for a semester so I am always interested in research related to his work.

**Comment by danbri** [comment]
currently just general learning. I had wrapped another C library in Python but this looks more modern, and comparing the two may teach me something...
